### ISSUE TITLE
vzpbackup fails to run with syntax error

### ISSUE THREAD

**Issue by burbilog** [andreasfaerber/vzpbackup#13]
xyzzy pts/0# /usr/local/bin/vzpbackup.sh --suspend=yes --backup-dir=/home/backup/  1025
    SUSPEND:                yes
    BACKUP_DIR:             /home/backup/
    WORK_DIR:               /home/backup/
    COMPRESS:               no
    COMPACT:                0
    BACKUP TTL:             0
    CTIDs to backup:                 1025
    EXCLUDE CTIDs:
    /usr/local/bin/vzpbackup.sh: line 262: syntax error near unexpected token `done'
    /usr/local/bin/vzpbackup.sh: line 262: `done'

Centos 6.5
Linux xyzzy 2.6.32-042stab090.5 #1 SMP Sat Jun 21 00:15:09 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andreasfaerber** [comment]
Sorry that this went without noticing.. Fixed it yesterday.

**Comment by andreasfaerber** [comment]
That was fixed some time ago
