### ISSUE TITLE
Don't allow multiple backups at once.

### ISSUE THREAD

**Issue by jcatello** [andreasfaerber/vzpbackup#16]
Is there anyway to ensure the script only does one backup at a time, example I noticed high IO on one of our servers and saw:

```
148230 be/4 root        0.00 B/s    0.00 B/s  0.00 % 99.99 % tar -cvf /mnt/nfs/vzpbackup_2083_server.asd.com_20160514010001.tar .
54695 be/4 root        0.00 B/s    0.00 B/s  0.00 % 99.99 % tar -cvf /mnt/nfs/vzpbackup_2116_sophia.asd.com_20160512010001.tar .
143948 be/4 root        0.00 B/s    0.00 B/s  0.00 % 97.05 % tar -cvf /mnt/nfs/vzpbackup_2094_server.asd.com_20160513010001.tar .
984019 be/4 root        0.00 B/s    0.00 B/s  0.00 % 97.05 % tar -cvf /mnt/nfs/vzpbackup_10713_server.asd.com_20160509010001.tar .
```

**Comment by andreasfaerber** [comment]
If you run the vzpbackup script you can use the command line to specify which containers to back up. The script will backup those containers sequentially.

Does that work for you? How do you invoke the backup?

**Comment by jcatello** [comment]
I run it like so:

`0 5 * * * /vzpbackup.sh --all  > /backup.log 2>&1`

**Comment by jcatello** [comment]
I think the issue may be with our NFS server to be honest. Sorry!
