### ISSUE TITLE
Backup Restore Error

### ISSUE THREAD

**Issue by hostingrajamani** [andreasfaerber/vzpbackup#6]
![restore](https://cloud.githubusercontent.com/assets/10419532/5629355/93f5efe6-95d8-11e4-95f5-5b73d7b91230.jpg)
Hello,

Thanks for the wonderful script, But unfortunately when I try to restore the backfile, I am having some error.

Please find the Error.

SRC VE CONF: dump/{26579950-ebd1-429f-bd51-01256e32bfdc}.ve.conf
ls: cannot access dump/{26579950-ebd1-429f-bd51-01256e32bfdc}.ve.*: No such file or directory
DUMPFILE: dump/{26579950-ebd1-429f-bd51-01256e32bfdc}

Command What I have Used to restore:
sh vzprestore.sh  --archive=/backup/vzpbackup_112_livechat.hostingraja.in_20150106184758.tar.gz  --container=111

I used these commands  vzpbackup.sh  vzprestore.sh for backup and restore

**Comment by andreasfaerber** [comment]
Greetings!

Does the restore actually work? It looks like the restore script is trying to restore additional vz configuration scripts like .premount and i am not treating the non-existence properly.. I will add that in one of the next versions then.

Please let me know if that is the issue or if the restore is faulty?

Regards,
Andreas

**Comment by hostingrajamani** [comment]
Hello Andreas,

Thank you very much for witting a excellent script.
Restore does not work, not sure why ?

I have written another script to take backup.

BTW, may I know about you ?

Mani

**Comment by andreasfaerber** [comment]
Greetings!

Thanks. Could you let me know what the issue with the restore is? Apart from the ls error there does not seem to be an issue from your screenshot: You have the resulting container 111 wich has been restored from a backup of the archive that was taken from a container with the ID 112 previously.

The vzlist shows the restored container. Are there any issues when you try to start up the restored container 111?

Regards,
Andreas

PS: Be sure to run the scripts with bash as they're using some bash specifics..

**Comment by hostingrajamani** [comment]
Hello Andreas,

When I restore the same error  was coming and then when I checked it using
vzlist, that container was missing.
So, I have written my own script to take backup.

**Comment by andreasfaerber** [comment]
Hi there! I have changed the vzprestore script to redirect the error message to /dev/null as there does not need to be an additional config file. So this is an error during restore but not an error for the restore itself.
