### ISSUE TITLE
Compact ploop image before doing the backup

### ISSUE THREAD

**Issue by tbrehm** [andreasfaerber/vzpbackup#7]
Hi,

it would be nice to add an option to run:

vzctl compact $CTID

on the vm before doing the backup. This will reduce the sizeof the root.hdd image before adding it to the backup file. Today I made a backup of a heavy used VM which had 74GB before compact and 35GB after running compact, so the backup size was more then 50% smaller after running compáct.

**Comment by andreasfaerber** [comment]
Added in 1.5. Thanks for the suggestion!
