### ISSUE TITLE
Use combined tar + gzip command when creating tar.gz file

### ISSUE THREAD

**Issue by tbrehm** [andreasfaerber/vzpbackup#8]
First I would like to say thank you for this nice backup script!

When creating a compressed image, the current script creates first a .tar file and later compresses it with gzip. The problem with this procedure is that a large amount of disk space is used.

Example:

root.hdd size is: 35GB
final backup size is of the tar.gz is: 15GB

The current script creates first the tar and then the gzip file, so it uses 50GB disk space during backup. Thats ok when you have plenty of free space, but if you have just 40GB left like in my case, then the backup will crash the system as I was not aware that it uses so much more space.

Using "tar cvf" only for uncompressed backups and e.g. "tar cvzf" for backups with gzip compression (or piping the tar output to gzip, if you prefer that) would greatly improve disk usage during backup as no temporary .tar file is created in that case..

**Comment by andreasfaerber** [comment]
Thanks for your feedback. Even though it took some time, i have added the compression options tgz, tbz and txz to compress the archive through tar.
