### ISSUE TITLE
Error while restoring dump

### ISSUE THREAD

**Issue by mhmuc** [andreasfaerber/vzpbackup#9]
Hi Andreas,

thank you very much for this great tool.
The documentation of the whole snapshotting in OVZ is so bad, that your tool really helps understanding it.

I tried to restore a ploop container with your restore-tool and I get the following error at the end:
"ls: cannot access dump/{9b5284b0-b51b-4723-a639-77ad82c3df69}.ve.*: No such file or directory"

I have the impression that there doesn't have to be a dumpfile and this is normal system behaviour. Am I right?

Thank you very much.
Gruß aus München!
Max

root@testserver:~# /root/bin/openvz/vzprestore.sh --archive=/vz/backup/vzpbackup_1000_testserver.testnetz.de_20150414151258.tar.gz --container=1000
Archive to restore:             /vz/backup/vzpbackup_1000_testserver.testnetz.de_20150414151258.tar.gz
Container to restore to:                1000
Confirm restore:                yes
Restoring VZ to:

Pre-Restore Checks..
Checking if container private directory (/var/lib/vz/private/1000) already exists..no
/var/lib/vz/private/1000 directory will be created during restore
Checking if container root directory (/var/lib/vz/root/1000) already exists..no
/var/lib/vz/root/1000 directory will be created during restore
Checking if container config file (/etc/vz/conf/1000.conf) already exists..no
/etc/vz/conf/1000.conf will be restored from backup

Actions taken for restore:
mkdir /var/lib/vz/root/1000
mkdir /var/lib/vz/private/1000
cd /var/lib/vz/private/1000
Extract backup archive into /var/lib/vz/private/1000
Create container config /etc/vz/conf/1000.conf
Amend container config VE_ROOT: /var/lib/vz/root/1000
Amend container config VE_PRIVATE: /var/lib/vz/private/1000

Confirm restore (yes/no): yes
Creating directory /var/lib/vz/root/1000
Creating direcotry /var/lib/vz/private/1000
cd into /var/lib/vz/private/1000
Extracting backup archive:
./
./Snapshots.xml
./dump/
./dump/{9b5284b0-b51b-4723-a639-77ad82c3df69}.ve.conf
./vzpbackup_snapshot
./root.hdd/
./root.hdd/root.hdd.{08c3e205-0315-449a-ab6c-9b42acf97631}
./root.hdd/DiskDescriptor.xml
./root.hdd/DiskDescriptor.xml.lck
./root.hdd/root.hdd
BACKUP_ID: 9b5284b0-b51b-4723-a639-77ad82c3df69
SRC VE CONF: dump/{9b5284b0-b51b-4723-a639-77ad82c3df69}.ve.conf
ls: cannot access dump/{9b5284b0-b51b-4723-a639-77ad82c3df69}.ve.*: No such file or directory
DUMPFILE: dump/{9b5284b0-b51b-4723-a639-77ad82c3df69}
No dump file found
      CTID      NPROC STATUS    IP_ADDR         HOSTNAME
      1000          - stopped   192.168.1.7     testserver.testnetz.de

**Comment by andreasfaerber** [comment]
You're correct. There does not need to be a config file in the dump directory. The error message will be redirected to /dev/null if no additional config exists.
